config/routes.rb
Rails.application.routes.draw do
  root 'galleries#index'
  resources :galleries, only: [:index, :show, :new, :create] do
    resources :paintings, only: [:new, :create]
  end

  resources :paintings, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :paintings

  validates :name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, numericality: true, length: { is: 5 }
end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :gallery

  validates :title, presence: true
  validates :year, presence: true, numericality: true, length: { is: 4}
  validates :artist, presence: true
  validates :gallery, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
    @paintings = @gallery.paintings
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      flash[:notice] = "Gallery added successfully."
      redirect_to gallery_path(@gallery)
    else
      flash.now[:notice] = @gallery.errors.full_messages
      render :new
    end
  end

  private

  def gallery_params
    params.require(:gallery).permit(:name, :city, :state, :description, :zip)
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new(painting_params)
    @painting.gallery = @gallery

    if @painting.save
      flash[:notice] = "Painting added successfully"
      redirect_to gallery_path(@gallery)
    else
      flash.now[:notice] = @painting.errors.full_messages
      render :new
    end
  end

  private

  def painting_params
    params.require(:painting).permit(:title, :artist, :year, :timestamp, :gallery_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/index.html.erb
<h1>Galleries</h1>

<ul>
  <% @galleries.each do |gallery|%>
    <li>
      <%= link_to gallery.name, gallery %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'Add New Gallery', new_gallery_path %></p>

app/views/galleries/new.html.erb
<h1>New Gallery Form</h1>

  <%= form_for(@gallery) do |f| %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_area :city %>
    </div>

    <div class="field">
      <%= f.label :state %><br />
      <%= f.text_area :state %>
    </div>

    <div class="field">
      <%= f.label :zip %><br />
      <%= f.text_area :zip %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>

    <div class="actions">
      <%= f.submit "Add Gallery"%>
    </div>
  <% end %>

app/views/galleries/show.html.erb
<h1><%= @gallery.name %></h1>

<ul>
  <li>
    <%= @gallery.city %>
    <%= @gallery.state %>
    <%= @gallery.zip %>
    <%= @gallery.description %>
  </li>
</ul>

<ul>
  <% @paintings.each do |painting| %>
  <li>
    <%= painting.title %>
    <%= painting.year %>
    <%= painting.artist %>
    <%= painting.created_at.strftime("%B %d %Y") %>
  </li>
  <% end %>
</ul>

<p><%= link_to 'Add a Painting', new_gallery_painting_path(@gallery) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gallery Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice.is_a?(Array) %>
    <% notice.each do |this_notice| %>
        <p class="notice"><%= this_notice %></p>
    <% end %>
  <% elsif notice %>
    <p class="notice"><%= notice %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/paintings/new.html.erb
<h1>New Painting Form for <%=@gallery.name %></h1>

  <%= form_for [@gallery, @painting] do |f| %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :year %><br />
      <%= f.text_area :year %>
    </div>

    <div class="field">
      <%= f.label :artist %><br />
      <%= f.text_area :artist %>
    </div>

    <div class="actions">
      <%= f.submit "Add Painting"%>
    </div>
  <% end %>